// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGN7SseTOJ0HcMzGJe_eYQvgI0GZioLE',
    appId: '1:482685883471:web:5d52a40a626c57deef063a',
    messagingSenderId: '482685883471',
    projectId: 'biblioteca-f9bc1',
    authDomain: 'biblioteca-f9bc1.firebaseapp.com',
    storageBucket: 'biblioteca-f9bc1.appspot.com',
    measurementId: 'G-JV0M8JDQJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6UMPMAPmjeDlkm_yszvDFK6eSu2uIqI',
    appId: '1:482685883471:android:cd873b1691d458ddef063a',
    messagingSenderId: '482685883471',
    projectId: 'biblioteca-f9bc1',
    storageBucket: 'biblioteca-f9bc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgEL-bTyr9ZJiczBJ7jEMGrnfjxF8XZFY',
    appId: '1:482685883471:ios:e0806c462a356c5bef063a',
    messagingSenderId: '482685883471',
    projectId: 'biblioteca-f9bc1',
    storageBucket: 'biblioteca-f9bc1.appspot.com',
    iosBundleId: 'com.example.flutterBiblioteca',
  );

}